close_when_open = true
theme = "omarchy-default"
theme_base = []
theme_location = ["~/.local/share/omarchy/default/walker/themes/"]
hotreload_theme = true
force_keyboard_focus = true
timeout = 60

[keys.ai]
run_last_response = ["ctrl e"]

[list]
max_entries = 200
cycle = true

[search]
placeholder = " Search..."

[builtins.hyprland_keybinds]
path = "~/.config/hypr/hyprland.conf"
hidden = true

[builtins.applications]
launch_prefix = "uwsm-app -- "
placeholder = " Search..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
icon = ""
hidden = true

[builtins.applications.actions]
enabled = false
hide_category = true

[builtins.bookmarks]
hidden = true

[[builtins.bookmarks.entries]]
label = "Omarchy - Github"
url = "https://github.com/malik-na/omarchy-mac"
keywords = ["omarchy", "github"]

[[builtins.bookmarks.entries]]
label = "Omarchy Manual"
url = "https://manuals.omamix.org/2/the-omarchy-manual"
keywords = ["omarchy"]

[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[providers.actions]
dmenu = [{ action = "select", default = true, bind = "Return" }]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]

bluetooth = [
  { action = "find", global = true, bind = "ctrl f", after = "AsyncClearReload" },
  { action = "trust", bind = "ctrl t", after = "AsyncReload" },
  { action = "untrust", bind = "ctrl t", after = "AsyncReload" },
  { action = "pair", bind = "Return", after = "AsyncReload" },
  { action = "remove", bind = "ctrl d", after = "AsyncReload" },
  { action = "connect", bind = "Return", after = "AsyncReload" },
  { action = "disconnect", bind = "Return", after = "AsyncReload" },
]

archlinuxpkgs = [
  { action = "install", bind = "Return", default = true },
  { action = "remove", bind = "Return" },
]

calc = [
  { action = "copy", default = true, bind = "Return" },
  { action = "delete", bind = "ctrl d", after = "AsyncReload" },
  { action = "save", bind = "ctrl s", after = "AsyncClearReload" },
]

websearch = [
  { action = "search", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
]

desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "start", label = "open+next", bind = "shift Return", after = "KeepOpen" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "AsyncReload" },
  { action = "pin", bind = "ctrl p", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl p", after = "AsyncReload" },
  { action = "pinup", bind = "ctrl n", after = "AsyncReload" },
  { action = "pindown", bind = "ctrl m", after = "AsyncReload" },
]

files = [
  { action = "open", default = true, bind = "Return" },
  { action = "opendir", label = "open dir", bind = "ctrl Return" },
  { action = "copypath", label = "copy path", bind = "ctrl shift c" },
  { action = "copyfile", label = "copy file", bind = "ctrl c" },
]

todo = [
  { action = "save", default = true, bind = "Return", after = "ClearReload" },
  { action = "delete", bind = "ctrl d", after = "ClearReload" },
  { action = "active", bind = "Return", after = "ClearReload" },
  { action = "inactive", bind = "Return", after = "ClearReload" },
  { action = "done", bind = "ctrl f", after = "ClearReload" },
  { action = "clear", bind = "ctrl x", after = "ClearReload", global = true },
]

runner = [
  { action = "run", default = true, bind = "Return" },
  { action = "runterminal", label = "run in terminal", bind = "shift Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
]

symbols = [
  { action = "run_cmd", label = "select", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
]

unicode = [
  { action = "run_cmd", label = "select", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
]

clipboard = [
  { action = "copy", default = true, bind = "Return" },
  { action = "remove", bind = "ctrl d", after = "ClearReload" },
  { action = "remove_all", global = true, label = "clear", bind = "ctrl shift d", after = "ClearReload" },
  { action = "toggle_images", global = true, label = "toggle images", bind = "ctrl i", after = "ClearReload" },
  { action = "edit", bind = "ctrl o" },
]
