force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
selection_wrap = true                                                       # wrap list if at bottom or top
theme = "omarchy-default"                                                   # theme to use
additional_theme_location = "~/.local/share/omarchy/default/walker/themes/"
hide_action_hints = true                                                    # globally hide the action hints

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
quick_activate = []

[columns]
symbols = 1 # providers to be queried by default

[providers]
max_results = 256 # 256 should be enough for everyone
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[builtins.applications.actions]
enabled = false
hide_category = true

[builtins.bookmarks]
hidden = true

[[builtins.bookmarks.entries]]
label = "Omarchy - Github"
url = "https://github.com/malik-na/omarchy-mac"
keywords = ["omarchy", "github"]

[[builtins.bookmarks.entries]]
label = "Omarchy Manual"
url = "https://manuals.omamix.org/2/the-omarchy-manual"
keywords = ["omarchy"]

[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3
prefix = "="

[builtins.windows]
switcher_only = true
hidden = true

[builtins.clipboard]
hidden = true

[builtins.commands]
hidden = true

[builtins.custom_commands]
hidden = true

[builtins.emojis]
name = "Emojis"
icon = ""
prefix = ":"

[builtins.symbols]
after_copy = ""
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = true
hidden = false
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[emergencies]]
text = "Restart Walker"
command = "omarchy-restart-walker"
